#!/bin/bash 
# Job name: 
#SBATCH --job-name=job01 
# 
# Partition: 
#SBATCH --partition=its-2a30-01-part
# 
# Specify one task: 
#SBATCH --ntasks-per-node=1 
# 
# Number of processors for single task needed for use case (example): 
#SBATCH --cpus-per-task=4
# 
#SBATCH --mem=50GB 
# 
#SBATCH --gpus-per-task=1 
# 
#SBATCH --gpu-bind=single:1 
# 
# Wall clock limit: 
#SBATCH --time=24:00:00 
# 
# Command(s) 
#SBATCH --chdir=/home/jw396/codespace
python3 Dissertation_patchcamelyon.py